### PR TITLE
A first try to configure the repo for building a debian package.

### PR DESCRIPTION
**Pull request by Kunzol**
The complex part is that on one side a linux module should be
created with dkms. On the other sider there is a binary which
needs to be compiled on package install because it depends on
the installed hardware. For compilation the user has to provide
some additional information, which is fetched via config-package
questions and answers.
Besides this some small test and calibration binaries are created
during the package build process.

Could only test this with my single hardware (KeDei) and hope
that it works similar with the other types of displays/touchscreens.

### CODE REVIEW

**Review by kpishere — APPROVED** [review]
thanks for sharing this Kunzol!  It is high time I learned how to do this too.  I'll give it a try with my Kedei setup as well, if all is good .. no rollbacks.

**Comment by Kunzol** [comment]
Seems this is the only way to contact you ...
My KeDei turns blank/white after some minutes. Any idea why?

**Comment by kpishere** [comment]
Yes, I think so. I presume, if you touch the screen or your running program refreshes the screen, it comes back to display what you expect?  In the module mpi3501.cpp, there are methods like TurnDisplayOff() that attempt to turn off LCD backlight during in-activity (no screen updates or touch events).  However, the KeDei does not support this -- I suspect it is hard wired this way and/or chip is a knockoff and does definitely not support it (driver circuitry in the package could cost more, i imagine).  I thought in the latest version I'd disabled turning off the display because, if you turn off the display, all you see is the white backlight then.  So, in you're application, you may have a screen-saviour behaviour to make the screen go black instead of turning off display.   Depending upon cmake build options, this code may be effective or not.  Also, check that you've got the latest version of this file.

**Comment by kpishere** [comment]
@Kunzol So, what do you do with this Debian stuff?  I don't get it, looks like quite a lot to learn.  I tried following this and didn't get far. (https://wiki.debian.org/HowToPackageForDebian).

**Comment by Kunzol** [comment]
I usually make Debian packages for easy installation in my work environment. Building and installing a package is usually faster than configuring 200 nodes manually. This is why I am quiet advanced in building Debian packages. 
As I saw your code for the LCDs and this will usually be installed on Raspbian which is Debian, I decided to add the code for making a Debian package. It might help others to install it.
At the end it was a bit more complex as I thought. I learned a lot, but this package is not a good example for a beginner.
Be aware that there are several "classes" of packages, config-packages, binary-packages, source-packages. Start building a config-package or binary-package, which is usually the easiest. Source-packages from a foreign-source-tree is usually the most complex. 

Try to read chapter 1,2,4,5,6 of the "Debian New Maintainers' Guide" as a starting point. 
https://www.debian.org/doc/manuals/maint-guide/index.en.html

Here is an intro for config-packages:
https://wiki.debian.org/ConfigPackages

**Pull request merged**
